// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeIncident = `-- name: CloseIncident :one
UPDATE incidents
SET status = 'CLOSED', closed_at = NOW()
WHERE id = $1
RETURNING id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at
`

func (q *Queries) CloseIncident(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, closeIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RuleID,
		&i.MetricID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOpenIncidents = `-- name: CountOpenIncidents :one
SELECT COUNT(*) FROM incidents WHERE status != 'CLOSED'
`

func (q *Queries) CountOpenIncidents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIncidents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenIncidentsByService = `-- name: CountOpenIncidentsByService :one
SELECT COUNT(*) FROM incidents
WHERE service_id = $1 AND status != 'CLOSED'
`

func (q *Queries) CountOpenIncidentsByService(ctx context.Context, serviceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenIncidentsByService, serviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (id, service_id, rule_id, metric_id, severity, status, message, opened_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at
`

type CreateIncidentParams struct {
	ID        string           `json:"id"`
	ServiceID string           `json:"service_id"`
	RuleID    string           `json:"rule_id"`
	MetricID  uuid.UUID        `json:"metric_id"`
	Severity  IncidentSeverity `json:"severity"`
	Status    IncidentStatus   `json:"status"`
	Message   *string          `json:"message"`
	OpenedAt  time.Time        `json:"opened_at"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ID,
		arg.ServiceID,
		arg.RuleID,
		arg.MetricID,
		arg.Severity,
		arg.Status,
		arg.Message,
		arg.OpenedAt,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RuleID,
		&i.MetricID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncident = `-- name: GetIncident :one
SELECT id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncident(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RuleID,
		&i.MetricID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at FROM incidents
ORDER BY opened_at DESC
LIMIT $1 OFFSET $2
`

type ListIncidentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RuleID,
			&i.MetricID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByService = `-- name: ListIncidentsByService :many
SELECT id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at FROM incidents
WHERE service_id = $1
ORDER BY opened_at DESC
LIMIT $2 OFFSET $3
`

type ListIncidentsByServiceParams struct {
	ServiceID string `json:"service_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListIncidentsByService(ctx context.Context, arg ListIncidentsByServiceParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByService, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RuleID,
			&i.MetricID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByStatus = `-- name: ListIncidentsByStatus :many
SELECT id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at FROM incidents
WHERE status = $1
ORDER BY opened_at DESC
LIMIT $2 OFFSET $3
`

type ListIncidentsByStatusParams struct {
	Status IncidentStatus `json:"status"`
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
}

func (q *Queries) ListIncidentsByStatus(ctx context.Context, arg ListIncidentsByStatusParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RuleID,
			&i.MetricID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIncidents = `-- name: ListOpenIncidents :many
SELECT id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at FROM incidents
WHERE status != 'CLOSED'
ORDER BY severity, opened_at DESC
LIMIT $1 OFFSET $2
`

type ListOpenIncidentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOpenIncidents(ctx context.Context, arg ListOpenIncidentsParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listOpenIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RuleID,
			&i.MetricID,
			&i.Severity,
			&i.Status,
			&i.Message,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE incidents
SET status = $2
WHERE id = $1
RETURNING id, service_id, rule_id, metric_id, severity, status, message, opened_at, closed_at, created_at, updated_at
`

type UpdateIncidentStatusParams struct {
	ID     string         `json:"id"`
	Status IncidentStatus `json:"status"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus, arg.ID, arg.Status)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RuleID,
		&i.MetricID,
		&i.Severity,
		&i.Status,
		&i.Message,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
