// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_comments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countIncidentComments = `-- name: CountIncidentComments :one
SELECT COUNT(*)::int FROM incident_comments WHERE incident_id = $1
`

func (q *Queries) CountIncidentComments(ctx context.Context, incidentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countIncidentComments, incidentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createIncidentComment = `-- name: CreateIncidentComment :one
INSERT INTO incident_comments (incident_id, author, content)
VALUES ($1, $2, $3)
RETURNING id, incident_id, author, content, created_at, updated_at
`

type CreateIncidentCommentParams struct {
	IncidentID string `json:"incident_id"`
	Author     string `json:"author"`
	Content    string `json:"content"`
}

func (q *Queries) CreateIncidentComment(ctx context.Context, arg CreateIncidentCommentParams) (IncidentComment, error) {
	row := q.db.QueryRow(ctx, createIncidentComment, arg.IncidentID, arg.Author, arg.Content)
	var i IncidentComment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncidentComment = `-- name: DeleteIncidentComment :exec
DELETE FROM incident_comments WHERE id = $1
`

func (q *Queries) DeleteIncidentComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIncidentComment, id)
	return err
}

const getIncidentComment = `-- name: GetIncidentComment :one
SELECT id, incident_id, author, content, created_at, updated_at FROM incident_comments WHERE id = $1
`

func (q *Queries) GetIncidentComment(ctx context.Context, id uuid.UUID) (IncidentComment, error) {
	row := q.db.QueryRow(ctx, getIncidentComment, id)
	var i IncidentComment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIncidentComments = `-- name: ListIncidentComments :many
SELECT id, incident_id, author, content, created_at, updated_at FROM incident_comments
WHERE incident_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIncidentComments(ctx context.Context, incidentID string) ([]IncidentComment, error) {
	rows, err := q.db.Query(ctx, listIncidentComments, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentComment{}
	for rows.Next() {
		var i IncidentComment
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentComment = `-- name: UpdateIncidentComment :one
UPDATE incident_comments
SET content = $2
WHERE id = $1
RETURNING id, incident_id, author, content, created_at, updated_at
`

type UpdateIncidentCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateIncidentComment(ctx context.Context, arg UpdateIncidentCommentParams) (IncidentComment, error) {
	row := q.db.QueryRow(ctx, updateIncidentComment, arg.ID, arg.Content)
	var i IncidentComment
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
