// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incident_events.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countIncidentEvents = `-- name: CountIncidentEvents :one
SELECT COUNT(*)::int FROM incident_events WHERE incident_id = $1
`

func (q *Queries) CountIncidentEvents(ctx context.Context, incidentID string) (int32, error) {
	row := q.db.QueryRow(ctx, countIncidentEvents, incidentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createIncidentEvent = `-- name: CreateIncidentEvent :one
INSERT INTO incident_events (incident_id, event_type, actor, old_value, new_value, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, incident_id, event_type, actor, old_value, new_value, metadata, created_at
`

type CreateIncidentEventParams struct {
	IncidentID string            `json:"incident_id"`
	EventType  IncidentEventType `json:"event_type"`
	Actor      *string           `json:"actor"`
	OldValue   *string           `json:"old_value"`
	NewValue   *string           `json:"new_value"`
	Metadata   []byte            `json:"metadata"`
}

func (q *Queries) CreateIncidentEvent(ctx context.Context, arg CreateIncidentEventParams) (IncidentEvent, error) {
	row := q.db.QueryRow(ctx, createIncidentEvent,
		arg.IncidentID,
		arg.EventType,
		arg.Actor,
		arg.OldValue,
		arg.NewValue,
		arg.Metadata,
	)
	var i IncidentEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.EventType,
		&i.Actor,
		&i.OldValue,
		&i.NewValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getIncidentEvent = `-- name: GetIncidentEvent :one
SELECT id, incident_id, event_type, actor, old_value, new_value, metadata, created_at FROM incident_events WHERE id = $1
`

func (q *Queries) GetIncidentEvent(ctx context.Context, id uuid.UUID) (IncidentEvent, error) {
	row := q.db.QueryRow(ctx, getIncidentEvent, id)
	var i IncidentEvent
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.EventType,
		&i.Actor,
		&i.OldValue,
		&i.NewValue,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listIncidentEvents = `-- name: ListIncidentEvents :many
SELECT id, incident_id, event_type, actor, old_value, new_value, metadata, created_at FROM incident_events
WHERE incident_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIncidentEvents(ctx context.Context, incidentID string) ([]IncidentEvent, error) {
	rows, err := q.db.Query(ctx, listIncidentEvents, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentEvent{}
	for rows.Next() {
		var i IncidentEvent
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.EventType,
			&i.Actor,
			&i.OldValue,
			&i.NewValue,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
