// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, incident_id, target, message)
VALUES ($1, $2, $3, $4)
RETURNING id, incident_id, target, message, sent_at, created_at
`

type CreateNotificationParams struct {
	ID         string `json:"id"`
	IncidentID string `json:"incident_id"`
	Target     string `json:"target"`
	Message    string `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.IncidentID,
		arg.Target,
		arg.Message,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Target,
		&i.Message,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, incident_id, target, message, sent_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Target,
		&i.Message,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, incident_id, target, message, sent_at, created_at FROM notifications
ORDER BY sent_at DESC
LIMIT $1 OFFSET $2
`

type ListNotificationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Target,
			&i.Message,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByIncident = `-- name: ListNotificationsByIncident :many
SELECT id, incident_id, target, message, sent_at, created_at FROM notifications
WHERE incident_id = $1
ORDER BY sent_at DESC
`

func (q *Queries) ListNotificationsByIncident(ctx context.Context, incidentID string) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Target,
			&i.Message,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextNotificationID = `-- name: NextNotificationID :one
SELECT CAST('N-' || nextval('notification_id_seq')::TEXT AS VARCHAR) AS id
`

func (q *Queries) NextNotificationID(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, nextNotificationID)
	var id string
	err := row.Scan(&id)
	return id, err
}
