// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const cleanupOldEvents = `-- name: CleanupOldEvents :exec
DELETE FROM outbox
WHERE created_at < NOW() - INTERVAL '7 days'
AND NOT EXISTS (
    SELECT 1 FROM outbox o2
    LEFT JOIN outbox_processing op ON o2.id = op.outbox_id
    WHERE o2.id = outbox.id AND op.outbox_id IS NULL
)
`

func (q *Queries) CleanupOldEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupOldEvents)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox (event_type, aggregate_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, created_at
`

type CreateOutboxEventParams struct {
	EventType     EventType `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (Outbox, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	var i Outbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getUnprocessedEvents = `-- name: GetUnprocessedEvents :many
SELECT o.id, o.event_type, o.aggregate_type, o.aggregate_id, o.payload, o.created_at
FROM outbox o
LEFT JOIN outbox_processing op ON o.id = op.outbox_id AND op.processor = $1
WHERE op.outbox_id IS NULL AND o.event_type = $2
ORDER BY o.created_at
LIMIT $3
`

type GetUnprocessedEventsParams struct {
	Processor string    `json:"processor"`
	EventType EventType `json:"event_type"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) GetUnprocessedEvents(ctx context.Context, arg GetUnprocessedEventsParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvents, arg.Processor, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedIncidentEvents = `-- name: GetUnprocessedIncidentEvents :many
SELECT o.id, o.event_type, o.aggregate_type, o.aggregate_id, o.payload, o.created_at
FROM outbox o
LEFT JOIN outbox_processing op ON o.id = op.outbox_id AND op.processor = $1
WHERE op.outbox_id IS NULL AND o.event_type IN ('INCIDENT_CREATED', 'INCIDENT_UPDATED')
ORDER BY o.created_at
LIMIT $2
`

type GetUnprocessedIncidentEventsParams struct {
	Processor string `json:"processor"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) GetUnprocessedIncidentEvents(ctx context.Context, arg GetUnprocessedIncidentEventsParams) ([]Outbox, error) {
	rows, err := q.db.Query(ctx, getUnprocessedIncidentEvents, arg.Processor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Outbox{}
	for rows.Next() {
		var i Outbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
INSERT INTO outbox_processing (outbox_id, processor)
VALUES ($1, $2)
ON CONFLICT (outbox_id, processor) DO NOTHING
`

type MarkEventProcessedParams struct {
	OutboxID  uuid.UUID `json:"outbox_id"`
	Processor string    `json:"processor"`
}

func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markEventProcessed, arg.OutboxID, arg.Processor)
	return err
}
