// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"
)

const createService = `-- name: CreateService :one
INSERT INTO services (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at
`

type CreateServiceParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.ID, arg.Name)
	var i Service
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, name, created_at FROM services WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, created_at FROM services ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
